name: GravitationBlocks
version: ${project.version}
main: cat.michal.GravitationBlocks
api-version: 1.16
authors: [ TheMichalPL ]
commands:
  gravitationstart:
    permission: gravitation.start
  gravitationstop:
    permission: gravitation.stop